#!/usr/bin/env python2

import mahotas
import milk

import mahotas.features
from imread import imread
from milk.utils import parallel

from glob import glob

import cPickle

parallel.set_max_processors()

def features_for(imname):
    img = mahotas.imread(imname)
    return mahotas.features.haralick(img).mean(0)

def learn_model(features, labels):
    learner = milk.defaultclassifier()
    return learner.train(features, labels)

if __name__ == "__main__":
    positives = glob("data/positives/*.jpg")
    negatives = glob("data/negatives/*.jpg")

    features = map(features_for, negatives+positives)
    labels = (["noshuttle"] * len(negatives)) + (["shuttle"] * len(positives))

    model = learn_model(features, labels)

    cPickle.dump(model, file("train.p", "wb"))
